### ISSUE TITLE
win10系统vminit空白

### ISSUE THREAD

**Issue by R9Ronaldo** [fe1w0/utools-vmware#1]
![图像 1](https://user-images.githubusercontent.com/11970631/129449049-f71d7dfd-78bf-45c1-996d-082f7d9d9c0e.jpg)

**Comment by imxiny** [comment]
我也是同样的问题

win10家庭中文版  21H1
utools v2.1.0
![https://testyao.oss-cn-beijing.aliyuncs.com/1629074166330.png](https://testyao.oss-cn-beijing.aliyuncs.com/1629074166330.png)

**Comment by fe1w0** [comment]
1.0.4 中修复
