### ISSUE TITLE
vmopen等命令没反应

### ISSUE THREAD

**Issue by ayuayue** [fe1w0/utools-vmware#3]
使用命令后可以显示列表,但是没执行,导入到开发者模式报错

![image](https://user-images.githubusercontent.com/44837611/145973484-ba0828d7-28ab-4add-8e9a-7447edcb1d64.png)

![image](https://user-images.githubusercontent.com/44837611/145973544-243e0d28-4034-4e6f-b3ca-dd4bb27444a5.png)

**Comment by fe1w0** [comment]
可以麻烦 粘贴一下 vmware.exe 的地址吗，可能是中间有空格的问题。
可以考虑通过链接方式，如添加一个 快捷方式 G:\vmware.exe.lnk,之后 再填写 为 G:\vmware.exe.lnk (注意 一定要有 lnk)，这个方式在 win10 和 win11 测试可行.抱歉现在才回
