### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Immortal-Sty** [fe1w0/utools-vmware#4]
vmrun和vmopen用了，没效果。
uTools版本2.5.1
Windows11
VMware16

**Comment by Lantern-r** [comment]
Mark 同上
utools: 2.5.2
Windows11
VMWare16.2.2
exe: C:\VM\vmware.exe.lnk
虚拟机文件目录: C:\VM\

![image](https://user-images.githubusercontent.com/64698811/156496579-3b8302c8-0033-4f5b-b46a-2a6658387c84.png)

**Comment by fe1w0** [comment]
1.0.7 版 应该修改这个问题了
