### ISSUE TITLE
UI BUG

### ISSUE THREAD

**Issue by Lantern-r** [fe1w0/utools-vmware#6]
windows版本: Win11
utools版本: 2.5.2
插件版本:  1.0.7

1. 保存按键消失
![image](https://user-images.githubusercontent.com/64698811/158143423-06f5476a-0932-439d-9cdf-a7d27c8833e3.png)

2. 显示重复
![image](https://user-images.githubusercontent.com/64698811/158143622-fb50cd30-9c1a-4dbf-8fb2-f0d8054ad391.png)

**Comment by fe1w0** [comment]
收到

**Comment by fe1w0** [comment]
已修复

**Comment by why1te** [comment]
![image](https://github.com/fe1w0/utools-vmware/assets/93355889/37970946-b991-4f98-848d-26f945885f71)
windows 11
插件1.0.10
保存按钮失效

**清空 utools 缓存数据后正常**
